import type { Metadata } from "next";
import { Toaster } from "@/components/ui/toaster";
import { Toaster as NewToaster } from "react-hot-toast";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body suppressHydrationWarning className={`antialiased h-screen`}>
        {children}
        <Toaster />
        <NewToaster />
      </body>
    </html>
  );
}
