export const songsData = {
  en: [
    { title: "Bohemian Rhapsody", artist: "Queen", genre: "Rock" },
    { title: "Sweet Caroline", artist: "Neil Diamond", genre: "Pop" },
    { title: "I Will Survive", artist: "Gloria Gaynor", genre: "Disco" },
    { title: "Sweet Home Alabama", artist: "Lynyrd Skynyrd", genre: "Rock" },
    { title: "Hey Jude", artist: "The Beatles", genre: "Rock" },
    { title: "I Want It That Way", artist: "Backstreet Boys", genre: "Pop" },
    { title: "Sweet Dreams", artist: "Eurythmics", genre: "Pop" },
    { title: "Sweet Child O' Mine", artist: "Guns N' Roses", genre: "Rock" },
    { title: "Dancing Queen", artist: "ABBA", genre: "Pop" },
    { title: "Wonderwall", artist: "Oasis", genre: "Rock" },
    { title: "Livin' on a Prayer", artist: "Bon Jovi", genre: "Rock" },
    { title: "Sweet Home Chicago", artist: "Blues Brothers", genre: "Blues" },
    {
      title: "I Will Always Love You",
      artist: "Whitney Houston",
      genre: "Pop",
    },
    { title: "Sweet Emotion", artist: "Aerosmith", genre: "Rock" },
    { title: "Hotel California", artist: "Eagles", genre: "Rock" },
    { title: "Sweet Thing", artist: "Van Morrison", genre: "Rock" },
    { title: "Yesterday", artist: "The Beatles", genre: "Rock" },
    { title: "Sweet Jane", artist: "Lou Reed", genre: "Rock" },
    { title: "Imagine", artist: "John Lennon", genre: "Rock" },
    { title: "Purple Rain", artist: "Prince", genre: "Rock" },
  ],
  fr: [
    { title: "La Vie En Rose", artist: "Édith Piaf", genre: "Chanson" },
    { title: "Ne Me Quitte Pas", artist: "Jacques Brel", genre: "Chanson" },
    { title: "Les Champs-Élysées", artist: "Joe Dassin", genre: "Pop" },
    {
      title: "Non, Je Ne Regrette Rien",
      artist: "Édith Piaf",
      genre: "Chanson",
    },
    { title: "La Mer", artist: "Charles Trenet", genre: "Chanson" },
    {
      title: "Pour Que Tu M'aimes Encore",
      artist: "Céline Dion",
      genre: "Pop",
    },
    { title: "La Bohème", artist: "Charles Aznavour", genre: "Chanson" },
    { title: "Je L'aime à Mourir", artist: "Francis Cabrel", genre: "Pop" },
    { title: "Les Lacs du Connemara", artist: "Michel Sardou", genre: "Pop" },
    { title: "Aux Champs-Élysées", artist: "Joe Dassin", genre: "Pop" },
    { title: "La Foule", artist: "Édith Piaf", genre: "Chanson" },
    {
      title: "Le Temps des Cathédrales",
      artist: "Bruno Pelletier",
      genre: "Musical",
    },
    { title: "Je Te Promets", artist: "Johnny Hallyday", genre: "Rock" },
    { title: "L'Été Indien", artist: "Joe Dassin", genre: "Pop" },
    {
      title: "Les Moulins de Mon Cœur",
      artist: "Michel Legrand",
      genre: "Chanson",
    },
    { title: "La Javanaise", artist: "Serge Gainsbourg", genre: "Chanson" },
    { title: "Mistral Gagnant", artist: "Renaud", genre: "Chanson" },
    { title: "Je Vole", artist: "Michel Sardou", genre: "Pop" },
    { title: "L'Aigle Noir", artist: "Barbara", genre: "Chanson" },
    { title: "La Quête", artist: "Jacques Brel", genre: "Chanson" },
  ],
  es: [
    { title: "Despacito", artist: "Luis Fonsi", genre: "Pop Latino" },
    { title: "La Bamba", artist: "Ritchie Valens", genre: "Rock Latino" },
    { title: "Macarena", artist: "Los del Río", genre: "Pop Latino" },
    { title: "Bailando", artist: "Enrique Iglesias", genre: "Pop Latino" },
    { title: "La Cucaracha", artist: "Traditional", genre: "Folk" },
    { title: "Guantanamera", artist: "Joseíto Fernández", genre: "Son Cubano" },
    { title: "Bésame Mucho", artist: "Consuelo Velázquez", genre: "Bolero" },
    { title: "El Rey", artist: "José Alfredo Jiménez", genre: "Ranchera" },
    { title: "Oye Como Va", artist: "Tito Puente", genre: "Salsa" },
    { title: "Vivir Mi Vida", artist: "Marc Anthony", genre: "Salsa" },
    { title: "La Vida Loca", artist: "Ricky Martin", genre: "Pop Latino" },
    { title: "Amor Prohibido", artist: "Selena", genre: "Tejano" },
    { title: "Cielito Lindo", artist: "Traditional", genre: "Ranchera" },
    { title: "Mi Gente", artist: "J Balvin", genre: "Reggaeton" },
    { title: "Bamboleo", artist: "Gipsy Kings", genre: "Rumba Flamenca" },
    { title: "El Perdón", artist: "Nicky Jam", genre: "Reggaeton" },
    { title: "Volare", artist: "Gipsy Kings", genre: "Rumba Flamenca" },
    { title: "La Camisa Negra", artist: "Juanes", genre: "Rock Latino" },
    { title: "Suavemente", artist: "Elvis Crespo", genre: "Merengue" },
    { title: "Asereje", artist: "Las Ketchup", genre: "Pop Latino" },
  ],
  it: [
    {
      title: "Nel blu dipinto di blu",
      artist: "Domenico Modugno",
      genre: "Pop",
    },
    { title: "O Sole Mio", artist: "Traditional", genre: "Napoletana" },
    { title: "Felicità", artist: "Al Bano & Romina Power", genre: "Pop" },
    {
      title: "Con Te Partirò",
      artist: "Andrea Bocelli",
      genre: "Classical Pop",
    },
    { title: "Bella Ciao", artist: "Traditional", genre: "Folk" },
    { title: "Gloria", artist: "Umberto Tozzi", genre: "Pop" },
    { title: "L'Italiano", artist: "Toto Cutugno", genre: "Pop" },
    { title: "Sara Perché Ti Amo", artist: "Ricchi e Poveri", genre: "Pop" },
    { title: "Azzurro", artist: "Adriano Celentano", genre: "Pop" },
    { title: "Il Mondo", artist: "Jimmy Fontana", genre: "Pop" },
    { title: "Quando Quando Quando", artist: "Tony Renis", genre: "Pop" },
    { title: "That's Amore", artist: "Dean Martin", genre: "Pop" },
    {
      title: "Tu Vuò Fà L'Americano",
      artist: "Renato Carosone",
      genre: "Swing",
    },
    { title: "Marina", artist: "Rocco Granata", genre: "Pop" },
    { title: "Caruso", artist: "Lucio Dalla", genre: "Pop" },
    { title: "Funiculì Funiculà", artist: "Traditional", genre: "Napoletana" },
    { title: "Torna a Surriento", artist: "Traditional", genre: "Napoletana" },
    { title: "Santa Lucia", artist: "Traditional", genre: "Napoletana" },
    { title: "Mambo Italiano", artist: "Rosemary Clooney", genre: "Pop" },
    {
      title: "Nel blu dipinto di blu",
      artist: "Domenico Modugno",
      genre: "Pop",
    },
  ],
};
