CREATE TABLE IF NOT EXISTS dedications (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  message TEXT NOT NULL,
  photo VARCHAR(255),
  recipients JSON DEFAULT NULL,
  songId INT UNSIGNED NOT NULL,
  FOREIGN KEY (songId) REFERENCES songs(id) ON DELETE CASCADE,
  userId INT UNSIGNED NOT NULL,
  FOREIGN KEY (userId) REFERENCES users(id) ON DELETE CASCADE,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP on UPDATE CURRENT_TIMESTAMP
) Engine = InnoDB;