CREATE TABLE IF NOT EXISTS songs (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  artist VARCHAR(255) NOT NULL,
  language VARCHAR(255) NOT NULL,
  genre VARCHAR(255) NOT NULL,
  duet BOOLEAN,
  sameSong VARCHAR(255) DEFAULT NULL,
  available BOOLEAN DEFAULT TRUE,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP on UPDATE CURRENT_TIMESTAMP
) Engine = InnoDB;